"""BLOK 9 - OHLCV Dogrulama ve Kurumsal Islem Duzeltmesi (validation paketi).

Bilesenler (SPEC BLOK 9):
- rules: 13 dogrulama kurali (kural kodlari), LayerStatus, RuleResult,
  BarContext, evaluate_bar, source_cross_check.
- calendar: TradingCalendar (hafta sonu + enjekte tatil + gelecek tarih).
- ohlcv_validator: OhlcvValidator, BarVerdict, SeriesVerdict,
  PromotionReport, ValidationConfig.
- corporate: CorporateAction, CorporateActionAdjuster, AdjustedSeries,
  AdjustedBar, OutlierExplanation, FrozenSnapshotStore, hata siniflari.
- sufficiency: classify_sufficiency, SufficiencyVerdict, SufficiencyConfig
  (6 durum).
- gate: ReleaseGate, ReleaseDecision (GATE_RELEASED / GATE_BLOCKED).

BLOK 6/7/8 ile entegrasyon enjeksiyonladir (identity_service,
corporate_lookup, source_compare, promoter); BLOK 8 PriceBar duck-typing
ile desteklenir (import zorunlu degildir).

Gercek ag YOK; stdlib only; deterministik; saat enjekte.
"""
from .calendar import (
    FUTURE_DATE,
    HOLIDAY,
    INVALID_DATE,
    WEEKEND,
    TradingCalendar,
)
from .corporate import (
    ACTION_TYPES,
    DUPLICATE_KAP_NOTICE,
    INVALID_CORPORATE_ACTION,
    NO_SYNTHETIC_HISTORY,
    SNAPSHOT_FROZEN,
    AdjustedBar,
    AdjustedSeries,
    CorporateAction,
    CorporateActionAdjuster,
    CorporateActionError,
    DuplicateKapNoticeError,
    FrozenSnapshotStore,
    InvalidCorporateActionError,
    NoSyntheticHistoryError,
    OutlierExplanation,
    SnapshotFrozenError,
    adjustment_factor,
    parse_ratio,
)
from .gate import (
    BLOCKING_SUFFICIENCY,
    GATE_BLOCKED,
    GATE_RELEASED,
    NO_RELEASABLE_BARS,
    ReleaseDecision,
    ReleaseGate,
)
from .ohlcv_validator import (
    BAR_NOT_FOUND,
    CORPORATE_CHECK_MISSING,
    PROMOTED_TO_VALIDATED,
    SOURCE_CHECK_MISSING,
    STATUS_NOT_CLEAN,
    BarVerdict,
    OhlcvValidator,
    PromotionReport,
    SeriesVerdict,
    ValidationConfig,
)
from .rules import (
    ALL_RULE_CODES,
    CLOSE_NOT_POSITIVE,
    CORPORATE_NOT_CHECKED,
    CURRENCY_MISMATCH,
    DUPLICATE_DATE,
    FATAL,
    HIGH_LT_PRICE,
    HIGH_NOT_POSITIVE,
    INFO,
    LOW_GT_PRICE,
    LOW_NOT_POSITIVE,
    NEGATIVE_VOLUME,
    NON_TRADING_DAY,
    OPEN_NOT_POSITIVE,
    SOURCE_DIVERGENCE_REVIEW,
    SYMBOL_OWNER_MISMATCH,
    UNEXPLAINED_OUTLIER,
    WARN,
    BarContext,
    LayerStatus,
    RuleResult,
    close_positive,
    corporate_checked,
    currency_ok,
    evaluate_bar,
    high_covers_all,
    high_positive,
    low_below_all,
    low_positive,
    no_duplicate_date,
    open_positive,
    outlier_explained,
    pct_change,
    source_cross_check,
    status_from_results,
    symbol_owner_ok,
    valid_trading_day,
    volume_non_negative,
)
from .sufficiency import (
    ALL_STATUSES,
    INSUFFICIENT_FOR_TECHNICAL,
    LIMITED_DATA,
    NEW_LISTING,
    PRICE_DATA_MISSING,
    REVIEW_REQUIRED,
    SUFFICIENT_DATA,
    SufficiencyConfig,
    SufficiencyVerdict,
    classify_sufficiency,
)

__all__ = [
    # rules: kodlar + severity
    "OPEN_NOT_POSITIVE",
    "HIGH_NOT_POSITIVE",
    "LOW_NOT_POSITIVE",
    "CLOSE_NOT_POSITIVE",
    "NEGATIVE_VOLUME",
    "HIGH_LT_PRICE",
    "LOW_GT_PRICE",
    "NON_TRADING_DAY",
    "DUPLICATE_DATE",
    "CURRENCY_MISMATCH",
    "SYMBOL_OWNER_MISMATCH",
    "UNEXPLAINED_OUTLIER",
    "CORPORATE_NOT_CHECKED",
    "SOURCE_DIVERGENCE_REVIEW",
    "ALL_RULE_CODES",
    "FATAL",
    "WARN",
    "INFO",
    # rules: tipler + fonksiyonlar
    "LayerStatus",
    "RuleResult",
    "BarContext",
    "evaluate_bar",
    "status_from_results",
    "pct_change",
    "open_positive",
    "high_positive",
    "low_positive",
    "close_positive",
    "volume_non_negative",
    "high_covers_all",
    "low_below_all",
    "valid_trading_day",
    "no_duplicate_date",
    "currency_ok",
    "symbol_owner_ok",
    "outlier_explained",
    "corporate_checked",
    "source_cross_check",
    # calendar
    "TradingCalendar",
    "WEEKEND",
    "HOLIDAY",
    "FUTURE_DATE",
    "INVALID_DATE",
    # validator
    "OhlcvValidator",
    "BarVerdict",
    "SeriesVerdict",
    "PromotionReport",
    "ValidationConfig",
    "BAR_NOT_FOUND",
    "STATUS_NOT_CLEAN",
    "SOURCE_CHECK_MISSING",
    "CORPORATE_CHECK_MISSING",
    "PROMOTED_TO_VALIDATED",
    # corporate
    "CorporateAction",
    "CorporateActionAdjuster",
    "AdjustedSeries",
    "AdjustedBar",
    "OutlierExplanation",
    "FrozenSnapshotStore",
    "CorporateActionError",
    "DuplicateKapNoticeError",
    "InvalidCorporateActionError",
    "NoSyntheticHistoryError",
    "SnapshotFrozenError",
    "adjustment_factor",
    "parse_ratio",
    "ACTION_TYPES",
    "DUPLICATE_KAP_NOTICE",
    "INVALID_CORPORATE_ACTION",
    "NO_SYNTHETIC_HISTORY",
    "SNAPSHOT_FROZEN",
    # sufficiency
    "classify_sufficiency",
    "SufficiencyVerdict",
    "SufficiencyConfig",
    "SUFFICIENT_DATA",
    "LIMITED_DATA",
    "NEW_LISTING",
    "INSUFFICIENT_FOR_TECHNICAL",
    "PRICE_DATA_MISSING",
    "REVIEW_REQUIRED",
    "ALL_STATUSES",
    # gate
    "ReleaseGate",
    "ReleaseDecision",
    "GATE_RELEASED",
    "GATE_BLOCKED",
    "NO_RELEASABLE_BARS",
    "BLOCKING_SUFFICIENCY",
]
